export enum AppActionType {
    CHANGE_PAGE = "CHANGE_PAGE",
    SET_DEPARTMENT_DATA_MODAL_MODE = "SET_DEPARTMENT_DATA_MODAL_MODE",
    SET_USER_DATA_MODAL_MODE = "SET_USER_DATA_MODAL_MODE",
    SET_ROLES = "SET_ROLES",
    SET_DEPARTMENTS = "SET_DEPARTMENTS",
    SET_USERS = "SET_USERS",
    SET_REFETCH_USER = "SET_REFETCH_USER",
    SET_REFETCH_DEPARTMENT = "SET_REFETCH_DEPARTMENT",
    SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
    SET_IS_WORKING = "SET_IS_WORKING",
    SET_ME = "SET_ME"
}