export enum UserActionType {
    SET_USER_USERNAME = "SET_USER_USERNAME",
    SET_USER_NAME = "SET_USER_NAME",
    SET_USER_SURNAME = "SET_USER_SURNAME",
    SET_USER_EMAIL = "SET_USER_EMAIL",
    SET_USER_PASSWORD = "SET_USER_PASSWORD",
    SET_DEPARTMENT = "SET_DEPARTMENT",
    SET_EDIT_INFO_USER = "SET_EDIT_INFO_USER",
    SET_ROLE = "SET_ROLE",    
    RESET_USER_INFO = "RESET_USER_INFO"

    

}